_target_: src.methods.dlight_sb_mm.DLightSBMM

optimizer: null

prior: ${prior}

dim: ${data.dim}
num_categories: ${data.num_categories}
num_potentials: 16
num_timesteps: ${prior.num_timesteps}
distr_init: uniform
entropy_warmup_steps: 20000
entropy_lambda: 0
sample_prob: 0.99
tau: 1.0
