throughput_monitor:
  _target_: src.callbacks.TrainOnlyThroughputMonitor
  batch_size_fn:
    _target_: src.utils.data.get_batch_size
    _partial_: true
  window_size: 10

gpu_memory_monitor:
  _target_: src.callbacks.GpuMemoryMonitor
  every_n_steps: 10
